### ISSUE TITLE
literally unplayable

### ISSUE THREAD

**Issue by bluziDev** [JimmyCushnie/TUNG#21]
can't see grass when looking straight down

**Comment by JimmyCushnie** [comment]
issue with Unity's terrain details system; they did it this way because the grass textures are meant to be viewed from the side, and look worse the less vertical it is. I could fix this by not letting you look down past 89 degrees, but this makes it feel really weird and off when you're trying to look straight down.

Marking as Won't Fix for now. 0.3 will have a redo of the game world, and I'll be taking another look at the grass system then...
