### ISSUE TITLE
buggy behavior with placing boards

### ISSUE THREAD

**Issue by Vykori** [JimmyCushnie/TUNG#25]
https://youtu.be/b6PCtqPHWis

world download:
https://drive.google.com/file/d/1y3zN_QEQz5Zo544TnyQeBZXovPGlB9be/view?usp=sharing

**Comment by Vykori** [comment]
I saved the boards and loaded them in a different world, placed them together the same way I did in the video, and the bug still occurs. but slightly differently.

**Comment by JimmyCushnie** [comment]
Fixed in 0.2.3. Thanks for reporting all these bugs :)

**Comment by JimmyCushnie** [comment]
Also, you were totally correct with what was happening. The game ran into an error while placing the board and a lot of essential functions didn't execute. The reason you had glitchy collision is because you were still moving around the board, but its collision geometry had been reactivated; as you moved it into yourself, it shoved you around.
