### ISSUE TITLE
Component clipping with board

### ISSUE THREAD

**Issue by chrizzz** [JimmyCushnie/TUNG#37]
In some rare cases a board can be placed such that it clips with a component, see the world attached: http://www.mediafire.com/file/pg6vgm3ywrjyali/clipping%20bug.zip

Interestingly, replacing the board works when the component is there, but replacing the component does not work when the board is already there.

**Comment by JimmyCushnie** [comment]
Okay, I've figured this one out.

When the game determines whether an object can be placed in a given location, it needs to get the worldspace scale of the object being placed. Previously, I was using Unity's built-in transform.lossyScale, which is (as its name suggests), lossy. I determined through experimentation that in worst-case scenarios, transform.lossyScale would be off by about 3%, so what I would do is use 97% of transform.lossyScale. What I didn't consider when doing that is that the margin of error would increase as the size of the object being placed increased. Because of this, the bigger a board is, the more it can clip into stuff.

For 0.3 I've created my own system for determining worldspace scale that is nearly lossless, and you can no longer slightly clip stuff like this. My testing shows it has negligible performance impact, as well.
