### ISSUE TITLE
Certain connections sometimes not allowed

### ISSUE THREAD

**Issue by chrizzz** [JimmyCushnie/TUNG#39]
It seems like certain connection are legal in some locations, but not others, see the attached screenshot.
![image](https://user-images.githubusercontent.com/22175805/38680558-ea1df4ec-3e66-11e8-8fc8-b7b5ae75a2a9.png)

**Comment by Stenodyon** [comment]
I managed to reproduce it:
![2018-04-12_15-33-24](https://user-images.githubusercontent.com/15184100/38680732-4ca9c712-3e67-11e8-8e1c-8ec756b1cc15.jpg)
Copied the board somewhere else:
![2018-04-12_15-33-43](https://user-images.githubusercontent.com/15184100/38680789-7197cbdc-3e67-11e8-8342-72a0143f594f.jpg)
[Here is the world](https://github.com/Iamsodarncool/TUNG/files/1903340/Close.Wiring.Bug.zip)
This is what I suspect happenend:
![supsition](https://user-images.githubusercontent.com/15184100/38680912-c04ae566-3e67-11e8-8f0b-62385abb695d.png)
But I don't know why it happens in some places and don't in others.

**Comment by JimmyCushnie** [comment]
You were correct in the cause of this bug, @Stenodyon. Six months ago, when I wrote the code for wires finding their pegs when they were loaded from the save, I really didn't know what I was doing. I couldn't figure out how to get the position of one end of the wire, and so I just did casts from the center of the wire outwards. As a result, all wires in the game must be able to find their points by casting from their center.

I've learned a lot since then, and for 0.3 I've made it so that the casts are always done from the ends of the wire, never its center. That fixes this bug. I believe the reason it only happened in some positions and not others was due to rounding errors.
