### ISSUE TITLE
Everything is slightly misaligned 

### ISSUE THREAD

**Issue by chrizzz** [JimmyCushnie/TUNG#4]
When rotating a square board, you can see the position changing ever so slightly: (watch in full-screen if you can't see it)
https://www.youtube.com/watch?v=9pQVXra1Tkk

This can cause some unexpected behaviour causing things to not fit that should fit:
https://www.youtube.com/watch?v=CfuXMg0_Lss

**Comment by Shaolin-Funk** [comment]
(version 0.1.5)

I've been having some problems with boards refusing to place and I was going to submit a new issue for it, but I realised that it's almost certainly due to this issue. I've attached a save in case it's helpful.

[Does not fit.zip](https://github.com/Iamsodarncool/TUNG/files/1677851/Does.not.fit.zip)

**Comment by JimmyCushnie** [comment]
Thank you. The save is extremely helpful!

**Comment by JimmyCushnie** [comment]
Fixed for 0.2
